/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NativeMessageQueue */

#ifndef _Included_NativeMessageQueue
#define _Included_NativeMessageQueue
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NativeMessageQueue
 * Method:    sendMsg
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_NativeMessageQueue_sendMsg
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     NativeMessageQueue
 * Method:    recvMsg
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_NativeMessageQueue_recvMsg
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     NativeMessageQueue
 * Method:    removeMsgQueue
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_NativeMessageQueue_removeMsgQueue
  (JNIEnv *, jobject, jint);

/*
 * Class:     NativeMessageQueue
 * Method:    initMsgQueue
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_NativeMessageQueue_initMsgQueue
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
